apiVersion: v1
kind: Template
labels:
  template: 
  selinon: 1.0.0
metadata:
  name: pgbouncer-imagestream
  annotations:
    description: Selinon pgbouncer image stream
    openshift.io/display-name: 'Selinon: pgbouncer'
    version: 1.0.0
    tags: poc,selinon,pgbouncer
    template.openshift.io/documentation-url: https://github.com/selinon
    template.openshift.io/long-description: Selinon pgbouncer image stream definition
    template.openshift.io/provider-display-name: Fridolin Pokorny

objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    labels:
      app: selinon
    name: pgbouncer
  spec:
    name: latest
